# Generated by Django 2.1.2 on 2018-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('started_time', models.CharField(max_length=20)),
                ('finished_time', models.CharField(max_length=20)),
                ('if_parent_dies', models.CharField(choices=[('cascade', 'Cascade'), ('ignore', 'Ignore'), ('retry', 'Retry')], default='IGNORE', max_length=10)),
                ('children', models.ManyToManyField(related_name='_application_children_+', to='applications.Application')),
            ],
        ),
    ]
