# Generated by Django 2.1.2 on 2018-11-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20181111_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitrequest',
            old_name='request_body',
            new_name='request_data',
        ),
    ]
